name: Build binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make android binaries
      run: make
    - name: make linux
      run: make local

    - uses: actions/upload-artifact@v4
      with:
        name: dump-arm64
        path: build/libs/arm64-v8a/dump
    - uses: actions/upload-artifact@v4
      with:
        name: dump-arm32
        path: build/libs/armeabi-v7a/dump
    - uses: actions/upload-artifact@v4
      with:
        name: sofix
        path: build/sofix
